main: de.miraculixx.bmbm.Main
version: 150
name: BlueMap-BannerMarker
description: "A BlueMap addition plugin. Give your players the option to place markers on the map via the vanilla banner feature!"
author: Miraculixx
website: https://miraculixx.de
load: STARTUP
api-version: 1.13
depend:
  - "BlueMap"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.1.0"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
  - "dev.jorel:commandapi-bukkit-kotlin:9.7.0"
  - "dev.jorel:commandapi-bukkit-shade:9.7.0"
  - "de.miraculixx:kpaper:1.1.1"

commands:
  banner-marker:
    permission: banner-marker.command.settings
    aliases:
      - bmb
